# Generated by Django 3.0.3 on 2022-10-26 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0002_dislikedmusic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislikedmusic',
            name='user_id',
        ),
        migrations.AddField(
            model_name='dislikedmusic',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dislikedmusic',
            name='music',
            field=models.ManyToManyField(blank=True, null=True, to='recommender.Musicdata'),
        ),
    ]
