# Generated by Django 3.2.15 on 2022-10-04 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0003_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(default='New Playlist', max_length=50)),
                ('playlist_id', models.IntegerField(unique=True)),
                ('playlist_owner', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='playlist_genre',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='playlist_id',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='playlist_name',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='playlist_subgenre',
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_songs',
            field=models.ManyToManyField(blank=True, to='recommender.Musicdata'),
        ),
    ]
