# Generated by Django 3.2.15 on 2022-10-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_auto_20221004_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_id',
            field=models.IntegerField(),
        ),
    ]
