# Generated by Django 3.2.15 on 2022-10-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_alter_playlist_playlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_songs',
            field=models.ManyToManyField(blank=True, null=True, to='recommender.Musicdata'),
        ),
    ]
