# Generated by Django 3.2.15 on 2022-10-12 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0006_alter_playlist_playlist_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_name',
            field=models.CharField(default='New Playlist', max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_owner',
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
