# Generated by Django 3.2.15 on 2022-10-12 03:18

from django.db import migrations, models
import recommender.models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_auto_20221011_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_id',
            field=models.CharField(default=recommender.models.unique_rand, max_length=8, unique=True),
        ),
    ]
