# Generated by Django 3.2.15 on 2022-10-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0011_auto_20221012_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentsearches',
            name='result1',
        ),
        migrations.AddField(
            model_name='recentsearches',
            name='result1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.RemoveField(
            model_name='recentsearches',
            name='result2',
        ),
        migrations.AddField(
            model_name='recentsearches',
            name='result2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.RemoveField(
            model_name='recentsearches',
            name='result3',
        ),
        migrations.AddField(
            model_name='recentsearches',
            name='result3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
