# Generated by Django 3.2.15 on 2022-10-17 16:14

from django.db import migrations, models
import recommender.models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0012_auto_20221012_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(default=recommender.models.unique_rand, max_length=8, unique=True)),
                ('track_name', models.TextField()),
                ('artist_id', models.TextField()),
                ('track_album_id', models.TextField()),
                ('track_album_release_date', models.IntegerField()),
                ('duration_ms', models.IntegerField()),
                ('playlist_id', models.ManyToManyField(to='recommender.Playlist')),
            ],
        ),
        migrations.CreateModel(
            name='artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.CharField(default=recommender.models.unique_rand, max_length=8, unique=True)),
                ('artist_name', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('subgenre', models.TextField(blank=True, null=True)),
                ('track_id', models.ManyToManyField(blank=True, null=True, to='recommender.song')),
            ],
        ),
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(default=recommender.models.unique_rand, max_length=8, unique=True)),
                ('album_name', models.TextField(blank=True, null=True)),
                ('genre', models.TextField()),
                ('subgenre', models.TextField()),
                ('artist_id', models.ManyToManyField(blank=True, null=True, to='recommender.artist')),
                ('track_id', models.ManyToManyField(blank=True, null=True, to='recommender.song')),
            ],
        ),
    ]
