# Generated by Django 3.2.15 on 2022-11-07 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0015_profileitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist_id',
            field=models.ManyToManyField(blank=True, to='recommender.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='track_id',
            field=models.ManyToManyField(blank=True, to='recommender.song'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='track_id',
            field=models.ManyToManyField(blank=True, to='recommender.song'),
        ),
        migrations.AlterField(
            model_name='dislikedmusic',
            name='music',
            field=models.ManyToManyField(blank=True, to='recommender.Musicdata'),
        ),
        migrations.AlterField(
            model_name='dislikedmusic',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_owner',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_songs',
            field=models.ManyToManyField(blank=True, to='recommender.Musicdata'),
        ),
        migrations.AlterField(
            model_name='profileitems',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
