# Generated by Django 3.2.15 on 2022-11-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0015_profileitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist_id',
        ),
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='album',
            name='subgenre',
        ),
        migrations.RemoveField(
            model_name='album',
            name='track_id',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='subgenre',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='track_id',
        ),
        migrations.AddField(
            model_name='album',
            name='album_artist',
            field=models.ManyToManyField(blank=True, null=True, to='recommender.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='album_genre',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='album_subgenre',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='album_tracks',
            field=models.ManyToManyField(blank=True, null=True, to='recommender.Musicdata'),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_genre',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_subgenre',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_tracks',
            field=models.ManyToManyField(blank=True, null=True, to='recommender.Musicdata'),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
