# Generated by Django 3.2.15 on 2022-11-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0016_auto_20221107_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_artist',
            field=models.ManyToManyField(blank=True, null=True, to='recommender.Artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
