# Generated by Django 3.2.15 on 2022-11-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0017_auto_20221108_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_release_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_artist',
            field=models.ManyToManyField(blank=True, null=True, to='recommender.Artist'),
        ),
        migrations.DeleteModel(
            name='song',
        ),
    ]
