# Generated by Django 3.2.15 on 2022-11-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0019_auto_20221109_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_artist',
            field=models.ManyToManyField(blank=True, null=True, to='recommender.Artist'),
        ),
    ]
