# Generated by Django 3.2.15 on 2022-11-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0023_auto_20221109_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_artist',
        ),
        migrations.AddField(
            model_name='album',
            name='album_artist',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_id',
            field=models.TextField(default='<function uuid4 at 0x0000029824D8F9A0>', editable=False, primary_key=True, serialize=False),
        ),
    ]
