# Generated by Django 3.2.15 on 2022-11-09 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0025_alter_artist_artist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_id',
            field=models.TextField(default=uuid.UUID('8a5b0008-eadb-48a1-95c5-b55ddc41f218'), primary_key=True, serialize=False),
        ),
    ]
