# Generated by Django 3.2.15 on 2022-11-14 16:20

from django.conf import settings
from django.db import migrations, models
import recommender.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0029_alter_artist_artist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikedmusic',
            name='music',
            field=models.ManyToManyField(blank=True, to='recommender.Musicdata'),
        ),
        migrations.AlterField(
            model_name='dislikedmusic',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profileitems',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(default=recommender.models.unique_rand, max_length=8, unique=True)),
                ('track_name', models.TextField()),
                ('artist_id', models.TextField()),
                ('track_album_id', models.TextField()),
                ('track_album_release_date', models.IntegerField()),
                ('duration_ms', models.IntegerField()),
                ('playlist_id', models.ManyToManyField(to='recommender.Playlist')),
            ],
        ),
    ]
