# Generated by Django 3.2.15 on 2022-11-21 16:49

from django.conf import settings
from django.db import migrations, models
import recommender.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0033_rename_profile_pic_profilepicture_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentSearches',
        ),
        migrations.AlterField(
            model_name='album',
            name='album_tracks',
            field=models.ManyToManyField(blank=True, to='recommender.Musicdata'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_tracks',
            field=models.ManyToManyField(blank=True, to='recommender.Musicdata'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_owner',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_songs',
            field=models.ManyToManyField(blank=True, to='recommender.Musicdata'),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=recommender.models.OverwriteStorage(), upload_to=recommender.models.ProfilePicture.pfp_rename),
        ),
    ]
