# Generated by Django 3.2.15 on 2022-11-19 16:20

from django.db import migrations, models
import recommender.models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0033_rename_profile_pic_profilepicture_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist_tracks',
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=recommender.models.OverwriteStorage(), upload_to=recommender.models.ProfilePicture.pfp_rename),
        ),
        migrations.DeleteModel(
            name='album',
        ),
        migrations.DeleteModel(
            name='artist',
        ),
    ]
