# Generated by Django 3.2.15 on 2022-11-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0034_auto_20221121_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSearches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=50)),
                ('from_year', models.IntegerField(blank=True, null=True)),
                ('to_year', models.IntegerField(blank=True, null=True)),
                ('result1', models.CharField(blank=True, max_length=25, null=True)),
                ('result2', models.CharField(blank=True, max_length=25, null=True)),
                ('result3', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
