# Generated by Django 3.2.15 on 2022-11-19 16:22

from django.db import migrations, models
import recommender.models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0034_auto_20221119_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.TextField(default=recommender.models.uniqueIDArtist, editable=False, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(blank=True, max_length=25, null=True)),
                ('artist_genre', models.CharField(blank=True, max_length=25, null=True)),
                ('artist_subgenre', models.CharField(blank=True, max_length=25, null=True)),
                ('artist_tracks', models.ManyToManyField(blank=True, null=True, to='recommender.Musicdata')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.TextField(blank=True, null=True)),
                ('album_name', models.CharField(blank=True, max_length=50, null=True)),
                ('album_artist', models.TextField(blank=True, null=True)),
                ('album_release_date', models.IntegerField(blank=True, null=True)),
                ('album_genre', models.CharField(blank=True, max_length=25, null=True)),
                ('album_subgenre', models.CharField(blank=True, max_length=25, null=True)),
                ('album_tracks', models.ManyToManyField(blank=True, null=True, to='recommender.Musicdata')),
            ],
        ),
    ]
