# Generated by Django 3.2.15 on 2022-11-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0037_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_albums',
            field=models.ManyToManyField(blank=True, null=True, to='recommender.Album'),
        ),
    ]
