# Generated by Django 3.2.15 on 2022-11-21 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0038_artist_artist_albums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_tracks',
            field=models.ManyToManyField(blank=True, to='recommender.Musicdata'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_owner',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_songs',
            field=models.ManyToManyField(blank=True, to='recommender.Musicdata'),
        ),
    ]
