# Generated by Django 3.2.15 on 2022-11-23 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0038_artist_artist_albums'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='album_tracks',
            field=models.ManyToManyField(blank=True, to='recommender.Musicdata'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_owner',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_songs',
            field=models.ManyToManyField(blank=True, to='recommender.Musicdata'),
        ),
        migrations.DeleteModel(
            name='DislikedMusic',
        ),
        migrations.AddField(
            model_name='dislikes',
            name='albums',
            field=models.ManyToManyField(blank=True, to='recommender.Album'),
        ),
        migrations.AddField(
            model_name='dislikes',
            name='artists',
            field=models.ManyToManyField(blank=True, to='recommender.Artist'),
        ),
        migrations.AddField(
            model_name='dislikes',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='recommender.Playlist'),
        ),
        migrations.AddField(
            model_name='dislikes',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='recommender.Musicdata'),
        ),
        migrations.AddField(
            model_name='dislikes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
