# Generated by Django 3.2.15 on 2022-11-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0039_auto_20221121_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_albums',
            field=models.ManyToManyField(blank=True, to='recommender.Album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_tracks',
            field=models.ManyToManyField(blank=True, to='recommender.Musicdata'),
        ),
    ]
