# Generated by Django 3.2.15 on 2022-11-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0040_auto_20221121_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentSearches',
        ),
    ]
