# Generated by Django 3.2.15 on 2022-11-21 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0040_auto_20221121_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentsearches',
            name='seach_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 21, 20, 41, 20, 173547, tzinfo=utc)),
        ),
    ]
