# Generated by Django 3.2.15 on 2022-11-21 20:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0041_recentsearches_seach_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsearches',
            name='seach_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 21, 20, 42, 2, 831494, tzinfo=utc)),
        ),
    ]
