# Generated by Django 3.2.15 on 2022-12-04 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0042_alter_recentsearches_search_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsearches',
            name='search_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
