# Generated by Django 3.2.15 on 2022-12-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0043_alter_recentsearches_search_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsearches',
            name='search_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
